INCLUDE(${CMAKE_ROOT}/Modules/FindPythonLibs.cmake)
IF(APPLE)
  SET(CMAKE_SHARED_MODULE_CREATE_C_FLAGS 
   "${CMAKE_SHARED_MODULE_CREATE_C_FLAGS} -Wl,-flat_namespace,-U,_environ")
  SET(CMAKE_SHARED_MODULE_CREATE_CXX_FLAGS 
   "${CMAKE_SHARED_MODULE_CREATE_CXX_FLAGS} -Wl,-flat_namespace,-U,_environ")
  SET(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS 
   "${CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS} -Wl,-flat_namespace,-U,_environ")
  SET(CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS 
   "${CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS} -Wl,-flat_namespace,-U,_environ")
ENDIF(APPLE)

